/*
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.
*/

namespace Problem002 {
  let prev = 1;
  let current = 2;
  const max = 4000000;
  let sum = 0;

  while (current < max) {
    [prev, current] = [current, prev + current];
    if (prev % 2 === 0) {
      sum += prev;
    }
  }

  console.log('Problem002, 合計 : ', sum);
}
